Update patch set 2
Patch Set 2:

@Mark
As far as I can tell, the CI failures don't seem to be related to these changes to the docs?

error: failed to get vol 'promenade-base.img'
error: Storage volume not found: no storage vol with matching path 'promenade-base.img'
curl: (6) Could not resolve host: artifacts-aic.atlantafoundry

Patch-set: 2
Label: Code-Review=0