Update patch set 1
Patch Set 1:

> Build Failed
 > 
 > http://10.24.20.18:30081/job/images/job/att-comdev/job/promenade/job/promenade/589/
 > : FAILURE
 > 
 > http://12.37.173.196:32775/repository/att-comdev-jenkins-logs/Codereview/att-comdev/promenade/407793/att-comdev/promenade-407793-6656.log
 > : SUCCESS

Looks like an upstream pip issue:

pip._vendor.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/94/03/14e68ad12e771a79cf96792f7158d68a7b3d8c7b2badf39e9ef1f65b57d6/Babel-2.5.3-py2.py3-none-any.whl (Caused by ResponseError('too many 503 error responses',))



recheck

Patch-set: 1
Reviewer: Mark Burnett <1011672@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Code-Review=0